### PR TITLE
Added generateStars() function to App.jsx

### PR DESCRIPTION
**Pull request by cwg83**
I whipped this up because I needed a way to generate star ratings for the Related component, and it seems like a few different components will need it. Let me know if you think it needs any tweaks - you can test it by passing down generateStars as a prop to your component and then doing {generateStars(4.5)} etc in your jsx

### CODE REVIEW

**Comment by Justin8912** [comment]
I noticed a couple things about the function btw that I'm gonna implement now:

1. The maximum number of stars depended on the rating that was input - so Im gonna change that default to 5
2. Also I'm gonna add empty white stars to pad the rest of the rating (for example if the rating was 2.5 stars, only 3 stars would show up in total)

**Comment by Justin8912** [comment]
Also, after talking about it with you and @sm-fm we decided to add the key property to each star so that now we should not have an issue with react.

**Comment by cwg83** [comment]
Just tested it in a replit, and working great. Thanks for catching that.

**Comment by Justin8912** [comment]
Now the partial star will shade relative to the rating

**Pull request merged**
