### PR TITLE
Did some minor setup

### PR DESCRIPTION
**Pull request by Justin8912**
This includes: 

- Setting up the server with express
- Serving the dist directory to the client in the server 
- Adding a package.json command for running the server file
- Adding a style sheet with a css reset at the top of the file

There is a current error which I think might be fixed when I pull the repo from the "The-World-is-Not-Enough" Repo directly instead of forking, but it says I am denied permission to access the .env file. To recreate this bug, uncomment line 11 in the server/index.js file and comment out the PATH declaration on line 13. Wasn't sure how to fix this but it may be a later issue.

### CODE REVIEW

**Comment by Justin8912** [comment]
@cwg83 @sm-fm @bossertjack Please review this setup if you can!

**Review by cwg83 — CHANGES_REQUESTED** [review]
I believe since we are using express.static to serve the static files we do not need to redirect to index.html on line 19 in server/index.js

**Comment by Justin8912** [comment]
Got it! Deleted the line and it worked just fine. Updated the file.

**Review by cwg83 — APPROVED** [review]
Everything looks good, thanks for handling this!

**Pull request merged**
